name: LearnPlugin
main: io.github.arewena.pluginMain
version: 1.0
api-version: 1.20
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:tap-core:4.9.8